doc.type.html
script
this.img=document.create element(covid)
img.src=http://www.google.com/intl/en_com/images/logo_plain.png
src=document getelementbyid(header)
src.appendchild(this.img)
filename=covidstrings33.js
java.awt graphics
<div id=header></div>
audio=new audio(audio_file mp3)
audio.play
random button
new button(set random color)
option button
new  button(change color)
public fun with graphics()
color panel=new j panel();
add(panel,center)
button panel
new j panel (new flowlayout(flowlayout.center)
buttonpanel.add(randombutton);
random.button add action listener(new action listener)
override 
public action performed(action event e){
random r=newrandom();
color panel.set background(new color(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13)))
num teams
total players=players per team
if players per team=zero
return zero
else 
return math floor total players/players per team
teamsgrouping=(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)
buttonpanel.add(optionbutton);
option button.add action listener(new action listener)
override 
public action performed(action event e)
color m=j color chooser.show dialog(fun with graphics.this)
if(multi!=null)
color panel set.background(multi)
this.add(button panel, border layout.south)
public static main(string [] args)
j frame f =new covid strings33()
f.set title(covid strings33)
f.set default close operation(exit_on_close);
f.set size
f.set visible(true);
<label id=lbl score>zero</label>
score=zero
if (mult == x*y)
[non-concatenated]
score+=ten
else:
score-=ten
if (mult ==x*y)
[concatenated]
score+=twenty
else:
score-=twenty
lbl score=document.get element by id(lbl score)
lbl.score.inner html=score
public action performed(action event e) 
system.out print.in (next button clicked)
frame.add(next button);
frame set visible true
object {a:one,b:two,c:three,d:four,e:five,f:six,g:seven,h:eight}
keys object keys(team)
entries object entries(obj);
value object=[team color]
covid strings team list33=[indigo isos,white transit angels,blue curve crushers,red protein spikers,green peacemakers,turquoise waves,orange rna messengers,black night riders]
covid strings phrase list33=[non-concatenated "one example involves him writing an essay about ukraine"
"a new covid surge from ukraine is probable due to russias invasion
"even if its not americas problem now it will eventually become americas problem"
"the who confirmed this on march2" 
"covids universe is everyones universe"
"nurse burnout nationally was worse post-pandemic than pre-pandemic"
"dont expect paid sick leave federally any time soon
"lauren boeberts health scare shows that covid anti-vaxers are frauds"
concatenated strings
"if"+"covid"+"was"+"ever"+"renamed"+"hopefully"+"it"+"would"+"take"+"less"+"than"+"100"+"years"
"calling"+"it"+"an"+"airborne"+"virus"+"shouldnt"+"take"+"100"+"years"+"either"
"at"+"least"+"covid"+"immunity"+"lasts"+"for"+"years"
"if"+"history"+"predicts"+"the"+"future"+"perhaps"+"it"+"might"+"predict"+"the"+"next"+"pandemic"
"perhaps"+"in"+"the"+"future"+"there"+"may"+"be"+"a"+"book"+"called"+"mask"+"of"+"the"+"covid"+"death"
"any"+"dialogue"+"involving"+"the"+"covid"+"high"+"five"+"is"+"better"+"though"
"progress"+"with"+"gaming"+"is"+"one"+"thing"+"covid"+"helped"+"with"
"getting"+"a"+"one"+"and"+"done"+"vaccine"+"for"+"infants"+"can"+"help"+"mitigate"+"covid"]
covid strings33 multiple choice list=[1:a post pandemic b for nurse jackie c for russians d in a nicu,2:a gaming b christmas c anti-vaxers d streaming,3:a ukraine b alaska c moldova d poland,4:a 50 b 100 c 40 d 70,5:a canadas b mexicos c nicaraguas d americas,6:a immunity b winter c relief d eradication,7:a present b future c past d age of the earth,8:a multiverse b marvel universe c universe d environment,9:a kung flu b wuhan virus c rsv d covid,10:a underwood b mcgough c boeberts d bacall,11:a infants b high school seniors c senior citizens d high school juniors,12:a treatise b essay c graphic novel d elegy,13:a soon b eventually c never d in due time,14:a yes b no] 
covid strings33 math problems list= [non-concatenated "if a line showing covid and gaming showed that as the pandemic forced more people to work remotely gaming increased what is the relationship"?,"if a line of covid and gaming with slope of 3 and a y intercept of 5 what would the y coordinate be if the x coordinate is 7"?,"if the previous point was reflected over the x axis what is the new point"?,"if the covid point(7,-26) was rotated 270 degrees counterclockwise what is the new point"?,"if the previous point was translated 5 units right and 13 units up what is the new point"?,"if the previous point was translated 15 units right and 7 units down what is the new point"?,"if that covid point was translated 1 unit left and 22 units up what is the new point"?,
concatenated"if"+"83"+"percent"+"believe"+"a"+"new"+"covid"+"surge"+"from"+"russias"+"invasion"+"of"+"ukraine"+Will+Come+To+America+What+Percent+Dont?,If+42+Percent+Strongly+Believe+What+Percent+Is+Mild?,If+The+Margin+Of+Error+Is+2.022+Percent+What+Is+The+Range?,If+A+Poll+Shows+That+98.9+Percent+Believe+That+Covid+Immunity+Lasting+For+Years+Is+Good+News+What+Percent+Dont?,If+97+Percent+Strongly+Believe+What+Percent+Is+Mild?,If+The+Margin+Of+Error+Is+1.719+Percent+What+Is+The+Range?]
Covid Strings33 Scrambled Phrase List=[Ovicd+Runse+Runbout,How+Ewns+Archm,Ovicd+Vinuerse] 
Covid Strings33 Sentence =(The Mainstreaming Of Covid Historical Fiction Will Come Soon )
Userin.Select Team
Import Meta.
Class MyClass
Constructor (Non-Concatenated)
Return Category
If Category==Math Problem:
Prompt
Log
Else:
Select From Multiple Choice
Myclass=New.Myclass(Concatenated)
Return Category
If Category==Math Problem:
Prompt
Log
Else:
Select From Multiple Choice
Import Syntax
Chart JS 
Def Gradient
Id=MyGradient
GradientUnits=UserSpaceOnUse
Function1=Covid Effect On Remote Work And Gaming
If Function1Slope>=1:
Return Direct Relationship
Else:
Return Inverse Or No Relationship
X1=0
Y1=5
X2=7
Y2= X2*3+Y1 
Stop Offset=0 Stop-Color=FF0000
Stop Offset=1 Stop Color=0000FF
<LinearGradient>
<Filter
Id=Linear1
