doc.type.html
script
filename=covid strings33 background.js
java.awt graphics 
this.img=document.create element(covid)
img.src=http://www.google.com/intl/en_com/images/logo_plain.png
src=document get element by id(header)
src.append child(this.img)
<div id=header></div>
audio=new audio(audio_file mp3)
audio.play
random button
new button (set random color)
option button
new  button (change color)
public fun with graphics(){
color panel=new panel();
add (panel,center )
button panel
new j panel (flowlayout.center)
button panel.add(random button);
random.button add action listener(new action listener)
override 
public action performed(action event e){
random r= new random();
color panel.set background(new color(rnextInt(13),)(rnextInt(13),)(rnextInt(13),)(rnextInt(13),)(rnextInt(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13),( rnextint(13),(rnextint(13)))
button panel.add(option button);
option button.add action listener(new action listener)
override 
public action performed(action event e)
color m=j color chooser.show dialog(fun with graphics.this)
if(multi!=null)
color panel set.background(multi)
this.add(button panel,border layout.south)
public static main(string [] args)
jframe f = new covid strings33()
f.set title(covid strings33)
f.set default close operation(exit_on_close);
f.setsize
f.set visible(true);
label id=lbl score>zero</label>
score=zero
if (mult ==x*y)
[non-concatenated]
score+=ten
else:
score-=ten
if (mult ==x*y)
[concatenated]
score+=twenty
else:
score-=twenty
lbl score=document.get element by id(LblScore)
lbl.score.inner html=score
public actionperformed(action event e) 
system.out print.in (next button clicked)
frame.add(next button);
frame set visible true
object {a:one,b:two,c:three,d:four,e:five,f:six,g:seven,h:eight}
keys object keys(team)
entries object entries(obj);
value object=[team color]
return filename
